import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { copyFile, mkdir, readFile, realpath, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { format, resolveConfig } from 'prettier';
import ts from 'typescript';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const artifact = path.join(root, 'vendor/tecton-react');
const provenance = JSON.parse(await readFile(path.join(artifact, 'provenance.json'), 'utf8'));
const arguments_ = process.argv.slice(2);
const checkOnly = arguments_.includes('--check');
const upstreamIndex = arguments_.indexOf('--upstream');

if (
  arguments_.some(
    (argument, index) =>
      argument !== '--check' &&
      argument !== '--upstream' &&
      !(upstreamIndex !== -1 && index === upstreamIndex + 1),
  ) ||
  (upstreamIndex !== -1 && !arguments_[upstreamIndex + 1])
) {
  throw new Error('Usage: node scripts/prepare-tecton.mjs [--check] [--upstream <checkout>]');
}

if (checkOnly && upstreamIndex !== -1) {
  throw new Error('--check is read-only and cannot be combined with --upstream.');
}

if (upstreamIndex !== -1) {
  const checkout = path.resolve(arguments_[upstreamIndex + 1]);
  const revision = execFileSync('git', ['-C', checkout, 'rev-parse', 'HEAD'], {
    encoding: 'utf8',
  }).trim();
  if (revision !== provenance.commit) {
    throw new Error(`Expected Tecton ${provenance.commit}; checkout is ${revision}.`);
  }
  for (const relative of Object.keys(provenance.sourceFiles)) {
    const source = path.join(checkout, provenance.packagePath, relative);
    const fingerprint = createHash('sha256')
      .update(await readFile(source))
      .digest('hex');
    if (fingerprint !== provenance.sourceFiles[relative]) {
      throw new Error(`Tecton checkout differs from the pinned source: ${relative}.`);
    }
    const destination = path.join(artifact, relative);
    await mkdir(path.dirname(destination), { recursive: true });
    await copyFile(source, destination);
  }
}

const fingerprints = {
  ...provenance.sourceFiles,
  ...provenance.thirdParty.shadcn.files,
};
for (const [relative, expected] of Object.entries(fingerprints)) {
  const contents = await readFile(path.join(artifact, relative));
  const actual = createHash('sha256').update(contents).digest('hex');
  if (actual !== expected) {
    throw new Error(`Tecton source checksum mismatch: ${relative}. Restore the pinned artifact.`);
  }
}

// Keep upstream generated source immutable. Only this distribution entry is adapted:
// use the CSS-only shadcn artifact and discover components inside the installed package.
const upstreamGlobals = await readFile(path.join(artifact, 'src/styles/globals.css'), 'utf8');
const distributedGlobals = upstreamGlobals
  .replace('@import "tailwindcss";', '@import "tailwindcss" source(none);')
  .replace('@import "shadcn/tailwind.css";', '@import "../third-party/shadcn/tailwind.css";')
  .replaceAll('@import "./', '@import "../src/styles/')
  .replace(/^@source .*;\r?\n/gm, '');
const generated = await format(
  `/* Generated by scripts/prepare-tecton.mjs from immutable upstream source. */\n${distributedGlobals}\n@source "../src";\n`,
  { ...(await resolveConfig(root)), parser: 'css' },
);
const destination = path.join(artifact, 'styles/globals.css');
if (checkOnly) {
  if ((await readFile(destination, 'utf8')) !== generated) {
    throw new Error('Tecton distribution CSS is stale. Run node scripts/prepare-tecton.mjs.');
  }
} else {
  await mkdir(path.dirname(destination), { recursive: true });
  await writeFile(destination, generated);
}

// Compile types with the upstream strict settings, independently of stricter author
// settings. Runtime source remains immutable and is compiled by Rspack consumers.
const installedArtifact = await realpath(path.join(root, 'node_modules/@tecton/react'));
const require = createRequire(path.join(installedArtifact, 'package.json'));
const cvaTypes = path.join(path.dirname(require.resolve('class-variance-authority')), 'types.d.ts');
const sourceRoot = path.join(installedArtifact, 'src');
const typeRoot = path.join(artifact, 'types');
const sourcePaths = Object.keys(provenance.sourceFiles).filter((relative) =>
  /\.tsx?$/.test(relative),
);
for (const relative of sourcePaths) {
  const fingerprint = createHash('sha256')
    .update(await readFile(path.join(installedArtifact, relative)))
    .digest('hex');
  if (fingerprint !== provenance.sourceFiles[relative]) {
    throw new Error(`Installed Tecton source differs: ${relative}. Reinstall the local package.`);
  }
}
const program = ts.createProgram(
  sourcePaths.map((relative) => path.join(installedArtifact, relative)),
  {
    target: ts.ScriptTarget.ES2022,
    lib: ['lib.es2022.d.ts', 'lib.dom.d.ts', 'lib.dom.iterable.d.ts'],
    module: ts.ModuleKind.ESNext,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    jsx: ts.JsxEmit.ReactJSX,
    strict: true,
    skipLibCheck: true,
    declaration: true,
    emitDeclarationOnly: true,
    allowImportingTsExtensions: true,
    rootDir: sourceRoot,
    outDir: typeRoot,
    types: ['react', 'react-dom'],
    typeRoots: [path.join(root, 'node_modules/@types')],
    paths: {
      // Name the public subpath explicitly; otherwise inferred CVA declarations can
      // reference pnpm's physical store path instead of this portable package export.
      'class-variance-authority/types': [cvaTypes],
      '@tecton/react/icons': [path.join(sourceRoot, 'icons/index.ts')],
      '@tecton/react/*': [path.join(sourceRoot, '*')],
    },
  },
);
const declarations = new Map();
const emit = program.emit(undefined, (file, contents) => declarations.set(file, contents));
const diagnostics = [...ts.getPreEmitDiagnostics(program), ...emit.diagnostics];
if (diagnostics.length > 0) {
  throw new Error(
    ts.formatDiagnosticsWithColorAndContext(diagnostics, {
      getCurrentDirectory: () => root,
      getCanonicalFileName: (file) => file,
      getNewLine: () => '\n',
    }),
  );
}
for (const [file, contents] of declarations) {
  if (checkOnly) {
    if ((await readFile(file, 'utf8')) !== contents) {
      throw new Error(`Tecton declarations are stale: ${path.relative(artifact, file)}.`);
    }
  } else {
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, contents);
  }
}

console.log(
  `Tecton ${provenance.commit.slice(0, 8)} verified: ${Object.keys(provenance.sourceFiles).length} upstream files; CSS and ${declarations.size} declarations ${checkOnly ? 'checked' : 'prepared'}.`,
);
